---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "service-spring-external"
    labels: 
      app: "spring"
  spec: 
    type: "NodePort"
    selector: 
      app: "spring"
    sessionAffinity: "None"
    ports: 
      - 
        name: "http"
        port: 80
        targetPort: 80
        protocol: "TCP"
      - 
        name: "https"
        port: 443
        targetPort: 443
        protocol: "TCP"
