---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: react
  namespace: %K8S_NAMESPACE%

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: react
  namespace: %K8S_NAMESPACE%
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["get", "list", "describe", "patch", "watch"]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "describe", "patch", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: react
  namespace: %K8S_NAMESPACE%
subjects:
  - kind: ServiceAccount
    name: react
    namespace: %K8S_NAMESPACE%
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: react

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring
  namespace: %K8S_NAMESPACE%

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spring
  namespace: %K8S_NAMESPACE%
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["get", "list", "describe", "patch", "watch"]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "describe", "patch", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring
  namespace: %K8S_NAMESPACE%
subjects:
  - kind: ServiceAccount
    name: react
    namespace: %K8S_NAMESPACE%
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: react